const SUPABASE_URL = "https://hrarefvqisavoqjxcooe.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyYXJlZnZxaXNhdm9xanhjb29lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2MTc0MzMsImV4cCI6MjA2MjE5MzQzM30.zsDnek6DhE3JPLhiEoTGxknc4MkdlFjGrpe62SF2JEI";
const supabase = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);
